name: 'Download and Cache File'
description: 'Cross-platform way to download and cache a file from a URL.'
author: 'valadaptive'

branding:
    icon: 'download'
    color: 'purple'

inputs:
    url:
        description: 'The URL to fetch'
        required: true
    destination:
        description:
            'The path to save the file to. Will be [default directory]/[URL file
            name] if not provided'
        required: false
    headers:
        description: 'The headers to send with the request'
        required: false
    additional-cache-key:
        description: 'Additional key to match against when caching the file'
        required: false
    max-age:
        description:
            'The maximum age of the cached file in seconds. If omitted or the
            empty string, the file will be cached indefinitely. If set to 0, the
            file will always be re-downloaded.'
        required: false

outputs:
    destination:
        description: 'The path the file was saved to.'

runs:
    using: node20
    main: dist/index.js
